### ISSUE TITLE
impossibility to disable/remove plugins

### ISSUE THREAD

**Issue by dh4rm4** [reversTeam/Sublivim#4]
It's impossible to disable/remove a plugin (NERD tree for example).
If the vimrc is changed, it goes back to it's sublivim configuration after relanch.
This makes it impossible to disable/remove plugins.

**Comment by reversTeam** [comment]
``` vim
" Open NERDTree with vim
let sbv_open_nerdtree_to_start=0
" Open Nerd Panel with a new tab
let sbv_open_nerdtree_with_new_tab=0
```
