### ISSUE TITLE
Relative Number

### ISSUE THREAD

**Issue by earthyearth** [reversTeam/Sublivim#6]
I can't seem to disable relative number. Can you help me?

**Comment by reversTeam** [comment]
I looking for implement that feature, before the end week

**Comment by earthyearth** [comment]
thanks :)

**Comment by earthyearth** [comment]
Did you guys go to 42 Paris?

**Comment by reversTeam** [comment]
Yes i'm student at 42 school of Paris

For your problem, you can add this line in your `~/.Sublivim/config_perso` to disable the relative number lines when you are in the insert mode.

```vim
let sbv_enable_numbers=0
```
