### ISSUE TITLE
[MACOS] Bug link when .vim already exists

### ISSUE THREAD

**Issue by tperraut** [reversTeam/Sublivim#7]
When the .vim folder already exist, the command `ln -s .Sublivim/vim $HOME/.vim` do something really strange and make the link like `ln -s .Sublivim/vim $HOME/.vim/vim`. The result of that thing is an output of error when launching vim and nothing working.

**Comment by reversTeam** [comment]
can you send me ?
`ls -la ${HOME}/.vim`
