### ISSUE TITLE
Sublivim not found

### ISSUE THREAD

**Issue by zenond** [reversTeam/Sublivim#8]
This command don't find the package to install in the shell.
curl http://install.sublivim.com | sh

**Comment by reversTeam** [comment]
Hello,

Sorry for the time, I am little busy. Normally, actually it's work

Thx for your interest

Théotime

2018-03-25 18:33 GMT+02:00 zenond <notifications@github.com>:

**Comment by reversTeam** [comment]
Sorry, for the delay, it's fix
